### PR TITLE
PR to add output_auxiliaries functionality for debugging

### PR DESCRIPTION
**Pull request by erialC-P**
This PR adds functionality to the elevation functions and CLI workflow to optionally output auxiliary files for debugging.

Setting `output_auxiliaries = True` in the CLI workflow will output the following four supporting files to assist with debugging of intertidal datasets:

- `freq`, an xr.DataArray showing the frequency of NDWI wetness over time in the area of interest (AOI)
- `corr`, an xr.DataArray showing the correlation between `freq` and tide height in the AOI
- `good_mask`, renamed as `candidate_intertidal_px` in the outputs, an xr.DataArray showing pixels that meet the `freq` and `corr` criteria for potential inclusion in intertidal analyses
- `misclassified_ds`, renamed as `misclassified_px_count`, an xr.DataArray counting the number of misclassifications per pixel of the elevation workflow.

### CODE REVIEW

**Comment by robbibt** [comment]
Thanks for this @erialC-P! Looking at the code, I think it might be possible to simplify this if we didn't worry about turning the auxiliary creation on and off at the lower level function level (e.g. `ds_to_flat`, `uncertainty`). At the moment that's forcing us to have a lot of "if/else" clauses to handle the different outputs we can get from those funcs - instead we could just have those funcs return all outputs by default, and then only export the ones we want at the very end depending on whether `output_auxiliaries` is True or False. The only disadvantage is that we'd waste a tiny bit of compute calculating the layers which we wouldn't end up using, but it might be worth it for a bit less complexity overall.

If this sounds OK, I might jump into this branch and have a go at updating this?

**Comment by erialC-P** [comment]
That's totally ok with me. Concern over that extra bit of compute was why I built it using the if/else's but if you think it would be a minimal cost to reduce the code complexity then I'm happy for you to go ahead. Thanks for looking it through.
Were you happy with the method to extract the count of misclassified pixels? I forgot to check whether misclassified_ds.ndwi.count(dim='time') == misclassified_ds.tide_m.count(dim='time')

**Comment by robbibt** [comment]
Have pushed an update with some changes - the main thing was doing a pretty major refactor to the `ds_to_flat` func: previously it was returning a mix of flattened and unflattened output, and I think this made it much more difficult to wrangle those datasets further down the workflow. The updated workflow is now:

1. `ds_to_flat` returns _only_ flattened (e.g. "z" dimension) outputs, for both the main `flat_ds` but also `corr`, `freq` etc
2. "auxiliary" outputs like `corr` and `freq` are then added to a new flattened `ds_aux`
3. `ds_aux` is then unflattened in a final step just like we do for the main `ds`
4. If `output_auxiliaries` is True, then we use the `export_intertidal_rasters` func to output those debug files as GeoTIFFs at the very end

I think this should make future changes a bit easier, as we don't need to keep track of which datasets are in 2D vs. flattened throughout the elevation workflow. Keeping things in flattened form might also reduce our memory footprint a bit too (haven't tested this!).

**Review by robbibt — APPROVED** [review]
Have pushed an update with some changes - the main thing was doing a pretty major refactor to the `ds_to_flat` func: previously it was returning a mix of flattened and unflattened output, and I think this made it much more difficult to wrangle those datasets further down the workflow. The updated workflow is now:

1. `ds_to_flat` returns _only_ flattened (e.g. "z" dimension) outputs, for both the main `flat_ds` but also `corr`, `freq` etc
2. "auxiliary" outputs like `corr` and `freq` are then added to a new flattened `ds_aux`
3. `ds_aux` is then unflattened in a final step just like we do for the main `ds`
4. If `output_auxiliaries` is True, then we use the `export_intertidal_rasters` func to output those debug files as GeoTIFFs at the very end

I think this should make future changes a bit easier, as we don't need to keep track of which datasets are in 2D vs. flattened throughout the elevation workflow. Keeping things in flattened form might also reduce our memory footprint a bit too (haven't tested this!).

**Pull request merged**
